name: enlace2021_pr

channels:
  - conda-forge

dependencies:
  - python
  - jupyterlab=3
  - pandas
  - pyarrow
  - openpyxl=2.6.0
  - matplotlib
  - seaborn=0.11.0
  - ipywidgets=7.6.2
  - scikit-learn=0.23.2
  - geopandas
  - plotly
